import { Prisma } from '@prisma/client';

export const categories: Prisma.CategoryCreateInput[] = [
  {
    name: 'Banery',
    slug: 'banery',
    description: 'Banery reklamowe na różne okazje - winylowe, siatkowe, płócienne',
    sortOrder: 1,
  },
  {
    name: 'Plakaty',
    slug: 'plakaty',
    description: 'Plakaty i afisze na papierze Citylight',
    sortOrder: 2,
  },
  {
    name: 'Naklejki',
    slug: 'naklejki',
    description: 'Naklejki i folie samoprzylepne',
    sortOrder: 3,
  },
  {
    name: 'Druki wielkoformatowe',
    slug: 'druki-wielkoformatowe',
    description: 'Druki na płótnie i papierze fotograficznym',
    sortOrder: 4,
  },
  {
    name: 'Folie backlit',
    slug: 'folie-backlit',
    description: 'Folie do oświetlanych konstrukcji',
    sortOrder: 5,
  },
];

export const products: Prisma.ProductCreateInput[] = [
  // Banery
  {
    name: 'Baner winylowy 440g',
    slug: 'baner-winylowy-440g',
    description: 'Baner winylowy o gramaturze 440g/m², idealny do druku zewnętrznego',
    category: { connect: { slug: 'banery' } },
    minWidth: 100,
    maxWidth: 1370,
    minHeight: 100,
    maxHeight: 3000,
    minArea: 0.1,
    maxArea: 50.0,
    basePrice: 45.00,
    options: {
      finishing: ['oczka', 'taśmy', 'cięcie'],
      rushOptions: ['standard', 'express_48h', 'express_24h', 'same_day'],
    },
  },
  {
    name: 'Baner winylowy 510g',
    slug: 'baner-winylowy-510g',
    description: 'Baner winylowy o gramaturze 510g/m², wyższa jakość',
    category: { connect: { slug: 'banery' } },
    minWidth: 100,
    maxWidth: 1370,
    minHeight: 100,
    maxHeight: 3000,
    minArea: 0.1,
    maxArea: 50.0,
    basePrice: 52.00,
    options: {
      finishing: ['oczka', 'taśmy', 'cięcie'],
      rushOptions: ['standard', 'express_48h', 'express_24h', 'same_day'],
    },
  },
  {
    name: 'Baner siatkowy',
    slug: 'baner-siatkowy',
    description: 'Baner siatkowy przepuszczający powietrze, idealny na rusztowania',
    category: { connect: { slug: 'banery' } },
    minWidth: 100,
    maxWidth: 1370,
    minHeight: 100,
    maxHeight: 3000,
    minArea: 0.1,
    maxArea: 50.0,
    basePrice: 48.00,
    options: {
      finishing: ['oczka', 'taśmy', 'cięcie'],
      rushOptions: ['standard', 'express_48h', 'express_24h'],
    },
  },

  // Plakaty
  {
    name: 'Plakat Citylight 135g',
    slug: 'plakat-citylight-135g',
    description: 'Plakat na papierze Citylight 135g/m²',
    category: { connect: { slug: 'plakaty' } },
    minWidth: 100,
    maxWidth: 1370,
    minHeight: 100,
    maxHeight: 2000,
    minArea: 0.1,
    maxArea: 20.0,
    basePrice: 25.00,
    options: {
      finishing: ['laminat', 'cięcie'],
      rushOptions: ['standard', 'express_48h', 'express_24h'],
    },
  },
  {
    name: 'Plakat Citylight 200g',
    slug: 'plakat-citylight-200g',
    description: 'Plakat na papierze Citylight 200g/m², wyższa gramatura',
    category: { connect: { slug: 'plakaty' } },
    minWidth: 100,
    maxWidth: 1370,
    minHeight: 100,
    maxHeight: 2000,
    minArea: 0.1,
    maxArea: 20.0,
    basePrice: 32.00,
    options: {
      finishing: ['laminat', 'cięcie'],
      rushOptions: ['standard', 'express_48h', 'express_24h'],
    },
  },

  // Naklejki
  {
    name: 'Naklejka Premium',
    slug: 'naklejka-premium',
    description: 'Naklejka na folii samoprzylepnej Premium',
    category: { connect: { slug: 'naklejki' } },
    minWidth: 50,
    maxWidth: 1370,
    minHeight: 50,
    maxHeight: 2000,
    minArea: 0.05,
    maxArea: 10.0,
    basePrice: 65.00,
    options: {
      finishing: ['cięcie', 'konturowanie'],
      rushOptions: ['standard', 'express_48h', 'express_24h'],
    },
  },
  {
    name: 'Naklejka Transparentna',
    slug: 'naklejka-transparentna',
    description: 'Naklejka na folii transparentnej',
    category: { connect: { slug: 'naklejki' } },
    minWidth: 50,
    maxWidth: 1370,
    minHeight: 50,
    maxHeight: 2000,
    minArea: 0.05,
    maxArea: 10.0,
    basePrice: 70.00,
    options: {
      finishing: ['cięcie', 'konturowanie'],
      rushOptions: ['standard', 'express_48h', 'express_24h'],
    },
  },

  // Druki wielkoformatowe
  {
    name: 'Druk na płótnie',
    slug: 'druk-na-plotnie',
    description: 'Druk na płótnie Canvas Premium',
    category: { connect: { slug: 'druki-wielkoformatowe' } },
    minWidth: 100,
    maxWidth: 1370,
    minHeight: 100,
    maxHeight: 2000,
    minArea: 0.1,
    maxArea: 15.0,
    basePrice: 95.00,
    options: {
      finishing: ['naciągnięcie na blejtram'],
      rushOptions: ['standard', 'express_48h'],
    },
  },
  {
    name: 'Druk fotograficzny',
    slug: 'druk-fotograficzny',
    description: 'Druk na papierze fotograficznym Premium',
    category: { connect: { slug: 'druki-wielkoformatowe' } },
    minWidth: 100,
    maxWidth: 1370,
    minHeight: 100,
    maxHeight: 2000,
    minArea: 0.1,
    maxArea: 10.0,
    basePrice: 120.00,
    options: {
      finishing: ['laminat', 'cięcie'],
      rushOptions: ['standard', 'express_48h'],
    },
  },

  // Folie backlit
  {
    name: 'Folia backlit Premium',
    slug: 'folia-backlit-premium',
    description: 'Folia do oświetlanych konstrukcji Premium',
    category: { connect: { slug: 'folie-backlit' } },
    minWidth: 100,
    maxWidth: 1370,
    minHeight: 100,
    maxHeight: 2000,
    minArea: 0.1,
    maxArea: 15.0,
    basePrice: 85.00,
    options: {
      finishing: ['cięcie'],
      rushOptions: ['standard', 'express_48h'],
    },
  },
];
